/********************************************************************************
** Form generated from reading UI file 'operator.ui'
**
** Created: Wed Nov 6 16:29:06 2013
**      by: Qt User Interface Compiler version 4.8.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_OPERATOR_H
#define UI_OPERATOR_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QComboBox>
#include <QtGui/QDialog>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QLineEdit>
#include <QtGui/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_Operator
{
public:
    QGroupBox *logingroup;
    QLabel *usernamelabel;
    QLabel *passwordlabel;
    QLineEdit *usernameedit;
    QLineEdit *passwordedit;
    QPushButton *loginbutton;
    QPushButton *logoutbutton;
    QGroupBox *operatorgroup;
    QGroupBox *addbatchgroup;
    QLineEdit *batchaddedit;
    QPushButton *batchaddbuton;
    QLabel *batchaddlabel;
    QGroupBox *modifygroup;
    QComboBox *batchcombobox;
    QPushButton *batchokbutton;
    QLabel *batchidlabel;
    QGroupBox *batcheditgroup;
    QGroupBox *initialweightgroup;
    QLabel *tarelabel;
    QLabel *gmlabel1;
    QLineEdit *tareweight;
    QLabel *gmlabel2;
    QLineEdit *fillweight;
    QLabel *filllabel;
    QLineEdit *parametername5;
    QGroupBox *tolerancegroup;
    QLabel *T3;
    QLabel *T2;
    QLineEdit *tolerance1;
    QLabel *T1;
    QLineEdit *tolerance2;
    QLineEdit *tolerance3;
    QCheckBox *parabox8;
    QLabel *label6;
    QCheckBox *parabox9;
    QCheckBox *parabox4;
    QCheckBox *parabox10;
    QLabel *label1;
    QLineEdit *value7;
    QLabel *parameterlabel2;
    QLabel *label2;
    QLabel *label8;
    QLabel *parameterlabel1;
    QLineEdit *parametername3;
    QLineEdit *parametername6;
    QLineEdit *value6;
    QLineEdit *value3;
    QLabel *label3;
    QLineEdit *parametername1;
    QLineEdit *value10;
    QCheckBox *parabox3;
    QLineEdit *parametername9;
    QLineEdit *value8;
    QLabel *label5;
    QCheckBox *parabox1;
    QLabel *valuelabel2;
    QLabel *valuelabel1;
    QLineEdit *parametername10;
    QLineEdit *parametername4;
    QLineEdit *parametername7;
    QLabel *label7;
    QLineEdit *value4;
    QLineEdit *parametername2;
    QCheckBox *parabox6;
    QCheckBox *parabox2;
    QLabel *label9;
    QCheckBox *parabox7;
    QLabel *label10;
    QLineEdit *parametername8;
    QCheckBox *parabox5;
    QLabel *label4;
    QLineEdit *value9;
    QLineEdit *value5;
    QLineEdit *value1;
    QLineEdit *value2;
    QPushButton *savebutton;
    QPushButton *resetbutton;
    QPushButton *cancelbutton;
    QGroupBox *deletebatchgroup;
    QLineEdit *batchdeleteedit;
    QPushButton *deletebutton;
    QLabel *batchdeletelabel;
    QGroupBox *passwordchangegroup;
    QLineEdit *oldpassedit;
    QLineEdit *newpassedit;
    QLabel *label;
    QLabel *newpasslabel;
    QPushButton *passokbutton;
    QPushButton *changebutton;
    QPushButton *passcancelbutton;
    QLabel *currentoperatorlabel;
    QLabel *loggedinas_label;
    QLabel *loggedintime_label;
    QLabel *loggedintime;

    void setupUi(QDialog *Operator)
    {
        if (Operator->objectName().isEmpty())
            Operator->setObjectName(QString::fromUtf8("Operator"));
        Operator->setEnabled(true);
        Operator->resize(623, 609);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/new/images/operator.png"), QSize(), QIcon::Normal, QIcon::Off);
        Operator->setWindowIcon(icon);
        logingroup = new QGroupBox(Operator);
        logingroup->setObjectName(QString::fromUtf8("logingroup"));
        logingroup->setGeometry(QRect(6, 5, 611, 51));
        usernamelabel = new QLabel(logingroup);
        usernamelabel->setObjectName(QString::fromUtf8("usernamelabel"));
        usernamelabel->setGeometry(QRect(8, 17, 71, 20));
        QFont font;
        font.setFamily(QString::fromUtf8("Arial Unicode MS"));
        font.setBold(true);
        font.setWeight(75);
        usernamelabel->setFont(font);
        usernamelabel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        passwordlabel = new QLabel(logingroup);
        passwordlabel->setObjectName(QString::fromUtf8("passwordlabel"));
        passwordlabel->setGeometry(QRect(243, 17, 61, 20));
        passwordlabel->setFont(font);
        passwordlabel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        usernameedit = new QLineEdit(logingroup);
        usernameedit->setObjectName(QString::fromUtf8("usernameedit"));
        usernameedit->setGeometry(QRect(83, 17, 141, 22));
        QFont font1;
        font1.setFamily(QString::fromUtf8("Arial Unicode MS"));
        font1.setPointSize(8);
        font1.setBold(false);
        font1.setWeight(50);
        usernameedit->setFont(font1);
        usernameedit->setMaxLength(30);
        usernameedit->setAlignment(Qt::AlignCenter);
        passwordedit = new QLineEdit(logingroup);
        passwordedit->setObjectName(QString::fromUtf8("passwordedit"));
        passwordedit->setGeometry(QRect(312, 17, 151, 22));
        passwordedit->setFont(font1);
        passwordedit->setMaxLength(30);
        passwordedit->setEchoMode(QLineEdit::Password);
        passwordedit->setAlignment(Qt::AlignCenter);
        loginbutton = new QPushButton(logingroup);
        loginbutton->setObjectName(QString::fromUtf8("loginbutton"));
        loginbutton->setGeometry(QRect(469, 17, 61, 23));
        logoutbutton = new QPushButton(logingroup);
        logoutbutton->setObjectName(QString::fromUtf8("logoutbutton"));
        logoutbutton->setEnabled(false);
        logoutbutton->setGeometry(QRect(535, 17, 61, 23));
        operatorgroup = new QGroupBox(Operator);
        operatorgroup->setObjectName(QString::fromUtf8("operatorgroup"));
        operatorgroup->setEnabled(true);
        operatorgroup->setGeometry(QRect(6, 60, 611, 531));
        addbatchgroup = new QGroupBox(operatorgroup);
        addbatchgroup->setObjectName(QString::fromUtf8("addbatchgroup"));
        addbatchgroup->setEnabled(true);
        addbatchgroup->setGeometry(QRect(10, 79, 291, 61));
        batchaddedit = new QLineEdit(addbatchgroup);
        batchaddedit->setObjectName(QString::fromUtf8("batchaddedit"));
        batchaddedit->setEnabled(true);
        batchaddedit->setGeometry(QRect(72, 23, 131, 22));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Arial Unicode MS"));
        font2.setPointSize(9);
        font2.setBold(true);
        font2.setWeight(75);
        batchaddedit->setFont(font2);
        batchaddedit->setAlignment(Qt::AlignCenter);
        batchaddbuton = new QPushButton(addbatchgroup);
        batchaddbuton->setObjectName(QString::fromUtf8("batchaddbuton"));
        batchaddbuton->setEnabled(true);
        batchaddbuton->setGeometry(QRect(207, 23, 71, 23));
        QFont font3;
        font3.setFamily(QString::fromUtf8("Arial Unicode MS"));
        batchaddbuton->setFont(font3);
        batchaddlabel = new QLabel(addbatchgroup);
        batchaddlabel->setObjectName(QString::fromUtf8("batchaddlabel"));
        batchaddlabel->setEnabled(true);
        batchaddlabel->setGeometry(QRect(15, 24, 51, 21));
        batchaddlabel->setFont(font);
        batchaddlabel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        modifygroup = new QGroupBox(operatorgroup);
        modifygroup->setObjectName(QString::fromUtf8("modifygroup"));
        modifygroup->setEnabled(true);
        modifygroup->setGeometry(QRect(10, 145, 591, 381));
        batchcombobox = new QComboBox(modifygroup);
        batchcombobox->setObjectName(QString::fromUtf8("batchcombobox"));
        batchcombobox->setEnabled(true);
        batchcombobox->setGeometry(QRect(199, 18, 161, 22));
        batchcombobox->setFont(font3);
        batchcombobox->setInsertPolicy(QComboBox::InsertAtTop);
        batchokbutton = new QPushButton(modifygroup);
        batchokbutton->setObjectName(QString::fromUtf8("batchokbutton"));
        batchokbutton->setEnabled(true);
        batchokbutton->setGeometry(QRect(365, 18, 71, 24));
        batchokbutton->setFont(font3);
        batchidlabel = new QLabel(modifygroup);
        batchidlabel->setObjectName(QString::fromUtf8("batchidlabel"));
        batchidlabel->setEnabled(true);
        batchidlabel->setGeometry(QRect(130, 18, 61, 21));
        batchidlabel->setFont(font);
        batchidlabel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        batcheditgroup = new QGroupBox(modifygroup);
        batcheditgroup->setObjectName(QString::fromUtf8("batcheditgroup"));
        batcheditgroup->setGeometry(QRect(7, 44, 578, 291));
        initialweightgroup = new QGroupBox(batcheditgroup);
        initialweightgroup->setObjectName(QString::fromUtf8("initialweightgroup"));
        initialweightgroup->setEnabled(true);
        initialweightgroup->setGeometry(QRect(10, 200, 245, 81));
        tarelabel = new QLabel(initialweightgroup);
        tarelabel->setObjectName(QString::fromUtf8("tarelabel"));
        tarelabel->setGeometry(QRect(14, 50, 71, 21));
        tarelabel->setFont(font);
        tarelabel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        gmlabel1 = new QLabel(initialweightgroup);
        gmlabel1->setObjectName(QString::fromUtf8("gmlabel1"));
        gmlabel1->setGeometry(QRect(205, 20, 21, 21));
        gmlabel1->setFont(font2);
        tareweight = new QLineEdit(initialweightgroup);
        tareweight->setObjectName(QString::fromUtf8("tareweight"));
        tareweight->setGeometry(QRect(95, 50, 101, 21));
        QFont font4;
        font4.setFamily(QString::fromUtf8("Arial Unicode MS"));
        font4.setPointSize(9);
        tareweight->setFont(font4);
        tareweight->setInputMethodHints(Qt::ImhDigitsOnly);
        tareweight->setMaxLength(8);
        tareweight->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        gmlabel2 = new QLabel(initialweightgroup);
        gmlabel2->setObjectName(QString::fromUtf8("gmlabel2"));
        gmlabel2->setGeometry(QRect(205, 50, 21, 21));
        gmlabel2->setFont(font2);
        fillweight = new QLineEdit(initialweightgroup);
        fillweight->setObjectName(QString::fromUtf8("fillweight"));
        fillweight->setGeometry(QRect(95, 20, 101, 21));
        fillweight->setFont(font4);
        fillweight->setInputMethodHints(Qt::ImhDigitsOnly);
        fillweight->setMaxLength(8);
        fillweight->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        filllabel = new QLabel(initialweightgroup);
        filllabel->setObjectName(QString::fromUtf8("filllabel"));
        filllabel->setGeometry(QRect(14, 20, 71, 21));
        filllabel->setFont(font);
        filllabel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        parametername5 = new QLineEdit(batcheditgroup);
        parametername5->setObjectName(QString::fromUtf8("parametername5"));
        parametername5->setEnabled(false);
        parametername5->setGeometry(QRect(47, 160, 114, 23));
        parametername5->setFont(font3);
        parametername5->setMaxLength(10);
        parametername5->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        tolerancegroup = new QGroupBox(batcheditgroup);
        tolerancegroup->setObjectName(QString::fromUtf8("tolerancegroup"));
        tolerancegroup->setEnabled(true);
        tolerancegroup->setGeometry(QRect(260, 200, 311, 81));
        T3 = new QLabel(tolerancegroup);
        T3->setObjectName(QString::fromUtf8("T3"));
        T3->setGeometry(QRect(209, 33, 21, 21));
        T3->setFont(font);
        T2 = new QLabel(tolerancegroup);
        T2->setObjectName(QString::fromUtf8("T2"));
        T2->setGeometry(QRect(110, 33, 21, 21));
        T2->setFont(font);
        tolerance1 = new QLineEdit(tolerancegroup);
        tolerance1->setObjectName(QString::fromUtf8("tolerance1"));
        tolerance1->setGeometry(QRect(30, 33, 71, 20));
        tolerance1->setFont(font4);
        tolerance1->setInputMethodHints(Qt::ImhDigitsOnly);
        tolerance1->setMaxLength(8);
        tolerance1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        T1 = new QLabel(tolerancegroup);
        T1->setObjectName(QString::fromUtf8("T1"));
        T1->setGeometry(QRect(10, 33, 21, 21));
        T1->setFont(font);
        tolerance2 = new QLineEdit(tolerancegroup);
        tolerance2->setObjectName(QString::fromUtf8("tolerance2"));
        tolerance2->setGeometry(QRect(130, 33, 71, 20));
        tolerance2->setFont(font4);
        tolerance2->setInputMethodHints(Qt::ImhDigitsOnly);
        tolerance2->setMaxLength(8);
        tolerance2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        tolerance3 = new QLineEdit(tolerancegroup);
        tolerance3->setObjectName(QString::fromUtf8("tolerance3"));
        tolerance3->setGeometry(QRect(230, 33, 71, 20));
        tolerance3->setFont(font4);
        tolerance3->setInputMethodHints(Qt::ImhDigitsOnly);
        tolerance3->setMaxLength(8);
        tolerance3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        parabox8 = new QCheckBox(batcheditgroup);
        parabox8->setObjectName(QString::fromUtf8("parabox8"));
        parabox8->setEnabled(true);
        parabox8->setGeometry(QRect(316, 100, 16, 22));
        label6 = new QLabel(batcheditgroup);
        label6->setObjectName(QString::fromUtf8("label6"));
        label6->setGeometry(QRect(291, 40, 18, 22));
        label6->setFont(font);
        label6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        parabox9 = new QCheckBox(batcheditgroup);
        parabox9->setObjectName(QString::fromUtf8("parabox9"));
        parabox9->setEnabled(true);
        parabox9->setGeometry(QRect(316, 130, 16, 22));
        parabox4 = new QCheckBox(batcheditgroup);
        parabox4->setObjectName(QString::fromUtf8("parabox4"));
        parabox4->setEnabled(true);
        parabox4->setGeometry(QRect(28, 130, 16, 22));
        parabox10 = new QCheckBox(batcheditgroup);
        parabox10->setObjectName(QString::fromUtf8("parabox10"));
        parabox10->setEnabled(true);
        parabox10->setGeometry(QRect(316, 160, 16, 22));
        label1 = new QLabel(batcheditgroup);
        label1->setObjectName(QString::fromUtf8("label1"));
        label1->setGeometry(QRect(2, 40, 18, 22));
        label1->setFont(font);
        label1->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        value7 = new QLineEdit(batcheditgroup);
        value7->setObjectName(QString::fromUtf8("value7"));
        value7->setEnabled(false);
        value7->setGeometry(QRect(453, 70, 114, 23));
        value7->setFont(font3);
        value7->setMaxLength(10);
        value7->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        parameterlabel2 = new QLabel(batcheditgroup);
        parameterlabel2->setObjectName(QString::fromUtf8("parameterlabel2"));
        parameterlabel2->setGeometry(QRect(334, 16, 114, 20));
        parameterlabel2->setFont(font);
        parameterlabel2->setAlignment(Qt::AlignCenter);
        label2 = new QLabel(batcheditgroup);
        label2->setObjectName(QString::fromUtf8("label2"));
        label2->setGeometry(QRect(2, 70, 18, 22));
        label2->setFont(font);
        label2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label8 = new QLabel(batcheditgroup);
        label8->setObjectName(QString::fromUtf8("label8"));
        label8->setGeometry(QRect(291, 100, 18, 22));
        label8->setFont(font);
        label8->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        parameterlabel1 = new QLabel(batcheditgroup);
        parameterlabel1->setObjectName(QString::fromUtf8("parameterlabel1"));
        parameterlabel1->setGeometry(QRect(47, 16, 114, 20));
        parameterlabel1->setFont(font);
        parameterlabel1->setAlignment(Qt::AlignCenter);
        parametername3 = new QLineEdit(batcheditgroup);
        parametername3->setObjectName(QString::fromUtf8("parametername3"));
        parametername3->setEnabled(false);
        parametername3->setGeometry(QRect(47, 100, 114, 23));
        parametername3->setFont(font3);
        parametername3->setMaxLength(10);
        parametername3->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        parametername6 = new QLineEdit(batcheditgroup);
        parametername6->setObjectName(QString::fromUtf8("parametername6"));
        parametername6->setEnabled(false);
        parametername6->setGeometry(QRect(334, 40, 114, 23));
        parametername6->setFont(font3);
        parametername6->setMaxLength(10);
        parametername6->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        value6 = new QLineEdit(batcheditgroup);
        value6->setObjectName(QString::fromUtf8("value6"));
        value6->setEnabled(false);
        value6->setGeometry(QRect(453, 40, 114, 23));
        value6->setFont(font3);
        value6->setMaxLength(10);
        value6->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        value3 = new QLineEdit(batcheditgroup);
        value3->setObjectName(QString::fromUtf8("value3"));
        value3->setEnabled(false);
        value3->setGeometry(QRect(167, 100, 114, 23));
        value3->setFont(font3);
        value3->setMaxLength(10);
        value3->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label3 = new QLabel(batcheditgroup);
        label3->setObjectName(QString::fromUtf8("label3"));
        label3->setGeometry(QRect(2, 100, 18, 22));
        label3->setFont(font);
        label3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        parametername1 = new QLineEdit(batcheditgroup);
        parametername1->setObjectName(QString::fromUtf8("parametername1"));
        parametername1->setEnabled(false);
        parametername1->setGeometry(QRect(47, 40, 114, 23));
        parametername1->setFont(font3);
        parametername1->setMaxLength(10);
        parametername1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        value10 = new QLineEdit(batcheditgroup);
        value10->setObjectName(QString::fromUtf8("value10"));
        value10->setEnabled(false);
        value10->setGeometry(QRect(453, 160, 114, 23));
        value10->setFont(font3);
        value10->setMaxLength(10);
        value10->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        parabox3 = new QCheckBox(batcheditgroup);
        parabox3->setObjectName(QString::fromUtf8("parabox3"));
        parabox3->setEnabled(true);
        parabox3->setGeometry(QRect(28, 100, 16, 22));
        parametername9 = new QLineEdit(batcheditgroup);
        parametername9->setObjectName(QString::fromUtf8("parametername9"));
        parametername9->setEnabled(false);
        parametername9->setGeometry(QRect(334, 130, 114, 23));
        parametername9->setFont(font3);
        parametername9->setMaxLength(10);
        parametername9->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        value8 = new QLineEdit(batcheditgroup);
        value8->setObjectName(QString::fromUtf8("value8"));
        value8->setEnabled(false);
        value8->setGeometry(QRect(453, 100, 114, 23));
        value8->setFont(font3);
        value8->setMaxLength(10);
        value8->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label5 = new QLabel(batcheditgroup);
        label5->setObjectName(QString::fromUtf8("label5"));
        label5->setGeometry(QRect(2, 160, 18, 22));
        label5->setFont(font);
        label5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        parabox1 = new QCheckBox(batcheditgroup);
        parabox1->setObjectName(QString::fromUtf8("parabox1"));
        parabox1->setEnabled(true);
        parabox1->setGeometry(QRect(28, 40, 16, 22));
        valuelabel2 = new QLabel(batcheditgroup);
        valuelabel2->setObjectName(QString::fromUtf8("valuelabel2"));
        valuelabel2->setGeometry(QRect(453, 16, 114, 20));
        valuelabel2->setFont(font);
        valuelabel2->setAlignment(Qt::AlignCenter);
        valuelabel1 = new QLabel(batcheditgroup);
        valuelabel1->setObjectName(QString::fromUtf8("valuelabel1"));
        valuelabel1->setGeometry(QRect(167, 16, 114, 20));
        valuelabel1->setFont(font);
        valuelabel1->setAlignment(Qt::AlignCenter);
        parametername10 = new QLineEdit(batcheditgroup);
        parametername10->setObjectName(QString::fromUtf8("parametername10"));
        parametername10->setEnabled(false);
        parametername10->setGeometry(QRect(334, 160, 114, 23));
        parametername10->setFont(font3);
        parametername10->setMaxLength(10);
        parametername10->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        parametername4 = new QLineEdit(batcheditgroup);
        parametername4->setObjectName(QString::fromUtf8("parametername4"));
        parametername4->setEnabled(false);
        parametername4->setGeometry(QRect(47, 130, 114, 23));
        parametername4->setFont(font3);
        parametername4->setMaxLength(10);
        parametername4->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        parametername7 = new QLineEdit(batcheditgroup);
        parametername7->setObjectName(QString::fromUtf8("parametername7"));
        parametername7->setEnabled(false);
        parametername7->setGeometry(QRect(334, 70, 114, 23));
        parametername7->setFont(font3);
        parametername7->setMaxLength(10);
        parametername7->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label7 = new QLabel(batcheditgroup);
        label7->setObjectName(QString::fromUtf8("label7"));
        label7->setGeometry(QRect(291, 70, 18, 22));
        label7->setFont(font);
        label7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        value4 = new QLineEdit(batcheditgroup);
        value4->setObjectName(QString::fromUtf8("value4"));
        value4->setEnabled(false);
        value4->setGeometry(QRect(167, 130, 114, 23));
        value4->setFont(font3);
        value4->setMaxLength(10);
        value4->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        parametername2 = new QLineEdit(batcheditgroup);
        parametername2->setObjectName(QString::fromUtf8("parametername2"));
        parametername2->setEnabled(false);
        parametername2->setGeometry(QRect(47, 70, 114, 23));
        parametername2->setFont(font3);
        parametername2->setMaxLength(10);
        parametername2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        parabox6 = new QCheckBox(batcheditgroup);
        parabox6->setObjectName(QString::fromUtf8("parabox6"));
        parabox6->setEnabled(true);
        parabox6->setGeometry(QRect(316, 40, 16, 22));
        parabox2 = new QCheckBox(batcheditgroup);
        parabox2->setObjectName(QString::fromUtf8("parabox2"));
        parabox2->setEnabled(true);
        parabox2->setGeometry(QRect(28, 70, 16, 22));
        label9 = new QLabel(batcheditgroup);
        label9->setObjectName(QString::fromUtf8("label9"));
        label9->setGeometry(QRect(291, 130, 18, 22));
        label9->setFont(font);
        label9->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        parabox7 = new QCheckBox(batcheditgroup);
        parabox7->setObjectName(QString::fromUtf8("parabox7"));
        parabox7->setEnabled(true);
        parabox7->setGeometry(QRect(316, 70, 16, 22));
        label10 = new QLabel(batcheditgroup);
        label10->setObjectName(QString::fromUtf8("label10"));
        label10->setGeometry(QRect(291, 160, 18, 22));
        label10->setFont(font);
        label10->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        parametername8 = new QLineEdit(batcheditgroup);
        parametername8->setObjectName(QString::fromUtf8("parametername8"));
        parametername8->setEnabled(false);
        parametername8->setGeometry(QRect(334, 100, 114, 23));
        parametername8->setFont(font3);
        parametername8->setMaxLength(10);
        parametername8->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        parabox5 = new QCheckBox(batcheditgroup);
        parabox5->setObjectName(QString::fromUtf8("parabox5"));
        parabox5->setEnabled(true);
        parabox5->setGeometry(QRect(28, 160, 16, 22));
        label4 = new QLabel(batcheditgroup);
        label4->setObjectName(QString::fromUtf8("label4"));
        label4->setGeometry(QRect(2, 130, 18, 22));
        label4->setFont(font);
        label4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        value9 = new QLineEdit(batcheditgroup);
        value9->setObjectName(QString::fromUtf8("value9"));
        value9->setEnabled(false);
        value9->setGeometry(QRect(453, 130, 114, 23));
        value9->setFont(font3);
        value9->setMaxLength(10);
        value9->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        value5 = new QLineEdit(batcheditgroup);
        value5->setObjectName(QString::fromUtf8("value5"));
        value5->setEnabled(false);
        value5->setGeometry(QRect(167, 160, 114, 23));
        value5->setFont(font3);
        value5->setMaxLength(10);
        value5->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        value1 = new QLineEdit(batcheditgroup);
        value1->setObjectName(QString::fromUtf8("value1"));
        value1->setEnabled(false);
        value1->setGeometry(QRect(167, 40, 114, 23));
        value1->setFont(font3);
        value1->setMaxLength(10);
        value1->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        value2 = new QLineEdit(batcheditgroup);
        value2->setObjectName(QString::fromUtf8("value2"));
        value2->setEnabled(false);
        value2->setGeometry(QRect(167, 70, 114, 23));
        value2->setFont(font3);
        value2->setMaxLength(10);
        value2->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        savebutton = new QPushButton(modifygroup);
        savebutton->setObjectName(QString::fromUtf8("savebutton"));
        savebutton->setGeometry(QRect(130, 340, 101, 31));
        savebutton->setFont(font);
        resetbutton = new QPushButton(modifygroup);
        resetbutton->setObjectName(QString::fromUtf8("resetbutton"));
        resetbutton->setGeometry(QRect(240, 340, 101, 31));
        resetbutton->setFont(font);
        resetbutton->setStyleSheet(QString::fromUtf8("color: rgb(212, 0, 3);"));
        cancelbutton = new QPushButton(modifygroup);
        cancelbutton->setObjectName(QString::fromUtf8("cancelbutton"));
        cancelbutton->setGeometry(QRect(350, 340, 101, 31));
        cancelbutton->setFont(font3);
        deletebatchgroup = new QGroupBox(operatorgroup);
        deletebatchgroup->setObjectName(QString::fromUtf8("deletebatchgroup"));
        deletebatchgroup->setEnabled(true);
        deletebatchgroup->setGeometry(QRect(310, 79, 291, 61));
        batchdeleteedit = new QLineEdit(deletebatchgroup);
        batchdeleteedit->setObjectName(QString::fromUtf8("batchdeleteedit"));
        batchdeleteedit->setEnabled(true);
        batchdeleteedit->setGeometry(QRect(73, 24, 131, 22));
        batchdeleteedit->setFont(font2);
        batchdeleteedit->setAlignment(Qt::AlignCenter);
        deletebutton = new QPushButton(deletebatchgroup);
        deletebutton->setObjectName(QString::fromUtf8("deletebutton"));
        deletebutton->setEnabled(true);
        deletebutton->setGeometry(QRect(208, 23, 71, 23));
        deletebutton->setFont(font3);
        deletebutton->setStyleSheet(QString::fromUtf8("color: rgb(212, 0, 3);"));
        batchdeletelabel = new QLabel(deletebatchgroup);
        batchdeletelabel->setObjectName(QString::fromUtf8("batchdeletelabel"));
        batchdeletelabel->setEnabled(true);
        batchdeletelabel->setGeometry(QRect(16, 24, 51, 21));
        batchdeletelabel->setFont(font);
        batchdeletelabel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        passwordchangegroup = new QGroupBox(operatorgroup);
        passwordchangegroup->setObjectName(QString::fromUtf8("passwordchangegroup"));
        passwordchangegroup->setGeometry(QRect(10, 18, 591, 57));
        oldpassedit = new QLineEdit(passwordchangegroup);
        oldpassedit->setObjectName(QString::fromUtf8("oldpassedit"));
        oldpassedit->setGeometry(QRect(77, 22, 131, 20));
        oldpassedit->setMaxLength(30);
        oldpassedit->setEchoMode(QLineEdit::Password);
        oldpassedit->setAlignment(Qt::AlignCenter);
        newpassedit = new QLineEdit(passwordchangegroup);
        newpassedit->setObjectName(QString::fromUtf8("newpassedit"));
        newpassedit->setEnabled(true);
        newpassedit->setGeometry(QRect(345, 22, 131, 20));
        newpassedit->setMaxLength(30);
        newpassedit->setEchoMode(QLineEdit::Password);
        newpassedit->setAlignment(Qt::AlignCenter);
        label = new QLabel(passwordchangegroup);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(4, 22, 71, 20));
        label->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        newpasslabel = new QLabel(passwordchangegroup);
        newpasslabel->setObjectName(QString::fromUtf8("newpasslabel"));
        newpasslabel->setEnabled(true);
        newpasslabel->setGeometry(QRect(271, 22, 71, 20));
        newpasslabel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        passokbutton = new QPushButton(passwordchangegroup);
        passokbutton->setObjectName(QString::fromUtf8("passokbutton"));
        passokbutton->setGeometry(QRect(210, 22, 51, 23));
        changebutton = new QPushButton(passwordchangegroup);
        changebutton->setObjectName(QString::fromUtf8("changebutton"));
        changebutton->setEnabled(true);
        changebutton->setGeometry(QRect(480, 22, 51, 23));
        passcancelbutton = new QPushButton(passwordchangegroup);
        passcancelbutton->setObjectName(QString::fromUtf8("passcancelbutton"));
        passcancelbutton->setEnabled(true);
        passcancelbutton->setGeometry(QRect(532, 22, 51, 23));
        currentoperatorlabel = new QLabel(Operator);
        currentoperatorlabel->setObjectName(QString::fromUtf8("currentoperatorlabel"));
        currentoperatorlabel->setGeometry(QRect(88, 592, 141, 16));
        QFont font5;
        font5.setFamily(QString::fromUtf8("Arial Unicode MS"));
        font5.setPointSize(8);
        font5.setBold(true);
        font5.setItalic(false);
        font5.setWeight(75);
        currentoperatorlabel->setFont(font5);
        currentoperatorlabel->setStyleSheet(QString::fromUtf8("color: rgb(252, 9, 0);"));
        currentoperatorlabel->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        loggedinas_label = new QLabel(Operator);
        loggedinas_label->setObjectName(QString::fromUtf8("loggedinas_label"));
        loggedinas_label->setGeometry(QRect(13, 592, 71, 16));
        QFont font6;
        font6.setFamily(QString::fromUtf8("Arial Unicode MS"));
        font6.setItalic(true);
        loggedinas_label->setFont(font6);
        loggedintime_label = new QLabel(Operator);
        loggedintime_label->setObjectName(QString::fromUtf8("loggedintime_label"));
        loggedintime_label->setGeometry(QRect(454, 592, 75, 16));
        loggedintime_label->setFont(font6);
        loggedintime_label->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        loggedintime = new QLabel(Operator);
        loggedintime->setObjectName(QString::fromUtf8("loggedintime"));
        loggedintime->setGeometry(QRect(535, 592, 81, 16));
        QFont font7;
        font7.setFamily(QString::fromUtf8("Arial Unicode MS"));
        font7.setBold(true);
        font7.setItalic(false);
        font7.setWeight(75);
        loggedintime->setFont(font7);
        loggedintime->setStyleSheet(QString::fromUtf8("color: rgb(8, 139, 24);"));
        QWidget::setTabOrder(usernameedit, passwordedit);
        QWidget::setTabOrder(passwordedit, loginbutton);
        QWidget::setTabOrder(loginbutton, logoutbutton);
        QWidget::setTabOrder(logoutbutton, oldpassedit);
        QWidget::setTabOrder(oldpassedit, passokbutton);
        QWidget::setTabOrder(passokbutton, newpassedit);
        QWidget::setTabOrder(newpassedit, changebutton);
        QWidget::setTabOrder(changebutton, passcancelbutton);
        QWidget::setTabOrder(passcancelbutton, batchaddedit);
        QWidget::setTabOrder(batchaddedit, batchaddbuton);
        QWidget::setTabOrder(batchaddbuton, batchdeleteedit);
        QWidget::setTabOrder(batchdeleteedit, deletebutton);
        QWidget::setTabOrder(deletebutton, batchcombobox);
        QWidget::setTabOrder(batchcombobox, batchokbutton);
        QWidget::setTabOrder(batchokbutton, parabox1);
        QWidget::setTabOrder(parabox1, parametername1);
        QWidget::setTabOrder(parametername1, value1);
        QWidget::setTabOrder(value1, parabox2);
        QWidget::setTabOrder(parabox2, parametername2);
        QWidget::setTabOrder(parametername2, value2);
        QWidget::setTabOrder(value2, parabox3);
        QWidget::setTabOrder(parabox3, parametername3);
        QWidget::setTabOrder(parametername3, value3);
        QWidget::setTabOrder(value3, parabox4);
        QWidget::setTabOrder(parabox4, parametername4);
        QWidget::setTabOrder(parametername4, value4);
        QWidget::setTabOrder(value4, parabox5);
        QWidget::setTabOrder(parabox5, parametername5);
        QWidget::setTabOrder(parametername5, value5);
        QWidget::setTabOrder(value5, parabox6);
        QWidget::setTabOrder(parabox6, parametername6);
        QWidget::setTabOrder(parametername6, value6);
        QWidget::setTabOrder(value6, parabox7);
        QWidget::setTabOrder(parabox7, parametername7);
        QWidget::setTabOrder(parametername7, value7);
        QWidget::setTabOrder(value7, parabox8);
        QWidget::setTabOrder(parabox8, parametername8);
        QWidget::setTabOrder(parametername8, value8);
        QWidget::setTabOrder(value8, parabox9);
        QWidget::setTabOrder(parabox9, parametername9);
        QWidget::setTabOrder(parametername9, value9);
        QWidget::setTabOrder(value9, parabox10);
        QWidget::setTabOrder(parabox10, parametername10);
        QWidget::setTabOrder(parametername10, value10);
        QWidget::setTabOrder(value10, fillweight);
        QWidget::setTabOrder(fillweight, tareweight);
        QWidget::setTabOrder(tareweight, tolerance1);
        QWidget::setTabOrder(tolerance1, tolerance2);
        QWidget::setTabOrder(tolerance2, tolerance3);
        QWidget::setTabOrder(tolerance3, savebutton);
        QWidget::setTabOrder(savebutton, resetbutton);
        QWidget::setTabOrder(resetbutton, cancelbutton);

        retranslateUi(Operator);

        QMetaObject::connectSlotsByName(Operator);
    } // setupUi

    void retranslateUi(QDialog *Operator)
    {
        Operator->setWindowTitle(QApplication::translate("Operator", "Operator Menu", 0, QApplication::UnicodeUTF8));
        logingroup->setTitle(QApplication::translate("Operator", "Login", 0, QApplication::UnicodeUTF8));
        usernamelabel->setText(QApplication::translate("Operator", "Username ", 0, QApplication::UnicodeUTF8));
        passwordlabel->setText(QApplication::translate("Operator", "Password", 0, QApplication::UnicodeUTF8));
        loginbutton->setText(QApplication::translate("Operator", "Login", 0, QApplication::UnicodeUTF8));
        logoutbutton->setText(QApplication::translate("Operator", "Logout", 0, QApplication::UnicodeUTF8));
        operatorgroup->setTitle(QApplication::translate("Operator", "Operator Options", 0, QApplication::UnicodeUTF8));
        addbatchgroup->setTitle(QApplication::translate("Operator", "Add Batch", 0, QApplication::UnicodeUTF8));
        batchaddbuton->setText(QApplication::translate("Operator", "Add", 0, QApplication::UnicodeUTF8));
        batchaddlabel->setText(QApplication::translate("Operator", "Batch ID", 0, QApplication::UnicodeUTF8));
        modifygroup->setTitle(QApplication::translate("Operator", "Modify Batch", 0, QApplication::UnicodeUTF8));
        batchokbutton->setText(QApplication::translate("Operator", "OK", 0, QApplication::UnicodeUTF8));
        batchidlabel->setText(QApplication::translate("Operator", "Batch ID", 0, QApplication::UnicodeUTF8));
        batcheditgroup->setTitle(QApplication::translate("Operator", "Batch Edit", 0, QApplication::UnicodeUTF8));
        initialweightgroup->setTitle(QApplication::translate("Operator", "Initial Weight", 0, QApplication::UnicodeUTF8));
        tarelabel->setText(QApplication::translate("Operator", "Tare Weight", 0, QApplication::UnicodeUTF8));
        gmlabel1->setText(QApplication::translate("Operator", "gm", 0, QApplication::UnicodeUTF8));
        gmlabel2->setText(QApplication::translate("Operator", "gm", 0, QApplication::UnicodeUTF8));
        filllabel->setText(QApplication::translate("Operator", "Fill Weight", 0, QApplication::UnicodeUTF8));
        tolerancegroup->setTitle(QApplication::translate("Operator", "Tolerance", 0, QApplication::UnicodeUTF8));
        T3->setText(QApplication::translate("Operator", "T3", 0, QApplication::UnicodeUTF8));
        T2->setText(QApplication::translate("Operator", "T2", 0, QApplication::UnicodeUTF8));
        T1->setText(QApplication::translate("Operator", "T1", 0, QApplication::UnicodeUTF8));
        parabox8->setText(QString());
        label6->setText(QApplication::translate("Operator", "6", 0, QApplication::UnicodeUTF8));
        parabox9->setText(QString());
        parabox4->setText(QString());
        parabox10->setText(QString());
        label1->setText(QApplication::translate("Operator", "1", 0, QApplication::UnicodeUTF8));
        parameterlabel2->setText(QApplication::translate("Operator", "Parameter", 0, QApplication::UnicodeUTF8));
        label2->setText(QApplication::translate("Operator", "2", 0, QApplication::UnicodeUTF8));
        label8->setText(QApplication::translate("Operator", "8", 0, QApplication::UnicodeUTF8));
        parameterlabel1->setText(QApplication::translate("Operator", "Parameter", 0, QApplication::UnicodeUTF8));
        label3->setText(QApplication::translate("Operator", "3", 0, QApplication::UnicodeUTF8));
        parabox3->setText(QString());
        label5->setText(QApplication::translate("Operator", "5", 0, QApplication::UnicodeUTF8));
        parabox1->setText(QString());
        valuelabel2->setText(QApplication::translate("Operator", "Value", 0, QApplication::UnicodeUTF8));
        valuelabel1->setText(QApplication::translate("Operator", "Value", 0, QApplication::UnicodeUTF8));
        label7->setText(QApplication::translate("Operator", "7", 0, QApplication::UnicodeUTF8));
        parabox6->setText(QString());
        parabox2->setText(QString());
        label9->setText(QApplication::translate("Operator", "9", 0, QApplication::UnicodeUTF8));
        parabox7->setText(QString());
        label10->setText(QApplication::translate("Operator", "10", 0, QApplication::UnicodeUTF8));
        parabox5->setText(QString());
        label4->setText(QApplication::translate("Operator", "4", 0, QApplication::UnicodeUTF8));
        savebutton->setText(QApplication::translate("Operator", "Save", 0, QApplication::UnicodeUTF8));
        resetbutton->setText(QApplication::translate("Operator", "Reset", 0, QApplication::UnicodeUTF8));
        cancelbutton->setText(QApplication::translate("Operator", "Close", 0, QApplication::UnicodeUTF8));
        deletebatchgroup->setTitle(QApplication::translate("Operator", "Delete Batch", 0, QApplication::UnicodeUTF8));
        deletebutton->setText(QApplication::translate("Operator", "Delete", 0, QApplication::UnicodeUTF8));
        batchdeletelabel->setText(QApplication::translate("Operator", "Batch ID", 0, QApplication::UnicodeUTF8));
        passwordchangegroup->setTitle(QApplication::translate("Operator", "Change Password", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("Operator", "Old Password", 0, QApplication::UnicodeUTF8));
        newpasslabel->setText(QApplication::translate("Operator", "New Password", 0, QApplication::UnicodeUTF8));
        passokbutton->setText(QApplication::translate("Operator", "OK", 0, QApplication::UnicodeUTF8));
        changebutton->setText(QApplication::translate("Operator", "Change", 0, QApplication::UnicodeUTF8));
        passcancelbutton->setText(QApplication::translate("Operator", "Cancel", 0, QApplication::UnicodeUTF8));
        currentoperatorlabel->setText(QString());
        loggedinas_label->setText(QApplication::translate("Operator", "Logged in as :", 0, QApplication::UnicodeUTF8));
        loggedintime_label->setText(QApplication::translate("Operator", "Logged in at :", 0, QApplication::UnicodeUTF8));
        loggedintime->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class Operator: public Ui_Operator {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_OPERATOR_H
