/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created: Mon Oct 7 15:58:51 2013
**      by: Qt User Interface Compiler version 4.8.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QFrame>
#include <QtGui/QGroupBox>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QMainWindow>
#include <QtGui/QPushButton>
#include <QtGui/QStatusBar>
#include <QtGui/QToolBar>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionFirst_Weight;
    QAction *actionSecond_Weight;
    QAction *actionView_Ticket;
    QAction *actionReport;
    QAction *actionSettings;
    QAction *actionHelp;
    QAction *actionExit;
    QWidget *centralWidget;
    QLabel *datelabel;
    QLabel *timelabel;
    QLabel *currentweightlabel;
    QLabel *currentdatetimelabel;
    QLabel *currentdatetimeedit;
    QLabel *currentweightedit;
    QFrame *backgroundframe;
    QLabel *headerlabel;
    QLabel *footerlabel;
    QLabel *exmonthlabel;
    QLabel *exyearlabel;
    QLabel *expirylabel;
    QGroupBox *menugroupbox;
    QPushButton *exitbutton;
    QPushButton *firstweightbutton;
    QPushButton *helpbutton;
    QPushButton *viewreportbutton;
    QPushButton *settingsbutton;
    QPushButton *viewticketbutton;
    QPushButton *secondweightbutton;
    QLabel *label;
    QLabel *exdateseperator;
    QGroupBox *tare_groupbox;
    QPushButton *tare_button;
    QToolBar *menubar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1178, 706);
        MainWindow->setBaseSize(QSize(0, 0));
        QFont font;
        font.setPointSize(10);
        font.setBold(false);
        font.setWeight(50);
        MainWindow->setFont(font);
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/new/resource/Secondweight.png"), QSize(), QIcon::Normal, QIcon::Off);
        MainWindow->setWindowIcon(icon);
        MainWindow->setStyleSheet(QString::fromUtf8(""));
        MainWindow->setIconSize(QSize(24, 24));
        actionFirst_Weight = new QAction(MainWindow);
        actionFirst_Weight->setObjectName(QString::fromUtf8("actionFirst_Weight"));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/new/resource/Firstweight.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionFirst_Weight->setIcon(icon1);
        QFont font1;
        font1.setPointSize(12);
        actionFirst_Weight->setFont(font1);
        actionFirst_Weight->setIconVisibleInMenu(true);
        actionSecond_Weight = new QAction(MainWindow);
        actionSecond_Weight->setObjectName(QString::fromUtf8("actionSecond_Weight"));
        actionSecond_Weight->setIcon(icon);
        actionView_Ticket = new QAction(MainWindow);
        actionView_Ticket->setObjectName(QString::fromUtf8("actionView_Ticket"));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/new/resource/Viewticket.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionView_Ticket->setIcon(icon2);
        actionReport = new QAction(MainWindow);
        actionReport->setObjectName(QString::fromUtf8("actionReport"));
        QIcon icon3;
        icon3.addFile(QString::fromUtf8(":/new/resource/Reports.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionReport->setIcon(icon3);
        actionSettings = new QAction(MainWindow);
        actionSettings->setObjectName(QString::fromUtf8("actionSettings"));
        QIcon icon4;
        icon4.addFile(QString::fromUtf8(":/new/resource/Settings.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSettings->setIcon(icon4);
        actionHelp = new QAction(MainWindow);
        actionHelp->setObjectName(QString::fromUtf8("actionHelp"));
        QIcon icon5;
        icon5.addFile(QString::fromUtf8(":/new/resource/Help.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionHelp->setIcon(icon5);
        actionExit = new QAction(MainWindow);
        actionExit->setObjectName(QString::fromUtf8("actionExit"));
        QIcon icon6;
        icon6.addFile(QString::fromUtf8(":/new/resource/Exit.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionExit->setIcon(icon6);
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        datelabel = new QLabel(centralWidget);
        datelabel->setObjectName(QString::fromUtf8("datelabel"));
        datelabel->setGeometry(QRect(410, 570, 31, 16));
        QFont font2;
        font2.setFamily(QString::fromUtf8("Arial Unicode MS"));
        font2.setBold(true);
        font2.setWeight(75);
        datelabel->setFont(font2);
        datelabel->setAutoFillBackground(true);
        timelabel = new QLabel(centralWidget);
        timelabel->setObjectName(QString::fromUtf8("timelabel"));
        timelabel->setGeometry(QRect(550, 570, 51, 16));
        timelabel->setFont(font2);
        timelabel->setAutoFillBackground(true);
        currentweightlabel = new QLabel(centralWidget);
        currentweightlabel->setObjectName(QString::fromUtf8("currentweightlabel"));
        currentweightlabel->setGeometry(QRect(640, 530, 261, 31));
        QPalette palette;
        QBrush brush(QColor(255, 255, 255, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(85, 0, 0, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(127, 0, 0, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(106, 0, 0, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(42, 0, 0, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(56, 0, 0, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        QBrush brush6(QColor(0, 0, 0, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush4);
        QBrush brush7(QColor(255, 255, 220, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        currentweightlabel->setPalette(palette);
        QFont font3;
        font3.setFamily(QString::fromUtf8("Arial Unicode MS"));
        font3.setPointSize(12);
        font3.setBold(true);
        font3.setWeight(75);
        currentweightlabel->setFont(font3);
        currentweightlabel->setAutoFillBackground(true);
        currentweightlabel->setAlignment(Qt::AlignCenter);
        currentdatetimelabel = new QLabel(centralWidget);
        currentdatetimelabel->setObjectName(QString::fromUtf8("currentdatetimelabel"));
        currentdatetimelabel->setGeometry(QRect(370, 530, 261, 31));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush4);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush4);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        currentdatetimelabel->setPalette(palette1);
        currentdatetimelabel->setFont(font3);
        currentdatetimelabel->setAutoFillBackground(true);
        currentdatetimelabel->setAlignment(Qt::AlignCenter);
        currentdatetimeedit = new QLabel(centralWidget);
        currentdatetimeedit->setObjectName(QString::fromUtf8("currentdatetimeedit"));
        currentdatetimeedit->setGeometry(QRect(370, 590, 261, 41));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush);
        QBrush brush8(QColor(127, 127, 127, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush8);
        QBrush brush9(QColor(170, 170, 170, 255));
        brush9.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush9);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette2.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette2.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette2.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush8);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush9);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette2.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush9);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush8);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette2.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette2.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        currentdatetimeedit->setPalette(palette2);
        QFont font4;
        font4.setFamily(QString::fromUtf8("Arial Unicode MS"));
        font4.setPointSize(11);
        font4.setBold(true);
        font4.setWeight(75);
        currentdatetimeedit->setFont(font4);
        currentdatetimeedit->setAutoFillBackground(true);
        currentdatetimeedit->setAlignment(Qt::AlignCenter);
        currentweightedit = new QLabel(centralWidget);
        currentweightedit->setObjectName(QString::fromUtf8("currentweightedit"));
        currentweightedit->setGeometry(QRect(640, 590, 261, 41));
        QPalette palette3;
        QBrush brush10(QColor(208, 0, 3, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush10);
        palette3.setBrush(QPalette::Active, QPalette::Button, brush);
        palette3.setBrush(QPalette::Active, QPalette::Light, brush);
        palette3.setBrush(QPalette::Active, QPalette::Midlight, brush);
        palette3.setBrush(QPalette::Active, QPalette::Dark, brush8);
        palette3.setBrush(QPalette::Active, QPalette::Mid, brush9);
        palette3.setBrush(QPalette::Active, QPalette::Text, brush10);
        palette3.setBrush(QPalette::Active, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Active, QPalette::ButtonText, brush10);
        palette3.setBrush(QPalette::Active, QPalette::Base, brush);
        palette3.setBrush(QPalette::Active, QPalette::Window, brush);
        palette3.setBrush(QPalette::Active, QPalette::Shadow, brush6);
        palette3.setBrush(QPalette::Active, QPalette::AlternateBase, brush);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipBase, brush7);
        palette3.setBrush(QPalette::Active, QPalette::ToolTipText, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush10);
        palette3.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Light, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Midlight, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Dark, brush8);
        palette3.setBrush(QPalette::Inactive, QPalette::Mid, brush9);
        palette3.setBrush(QPalette::Inactive, QPalette::Text, brush10);
        palette3.setBrush(QPalette::Inactive, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ButtonText, brush10);
        palette3.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Window, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::Shadow, brush6);
        palette3.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush7);
        palette3.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush10);
        palette3.setBrush(QPalette::Disabled, QPalette::Button, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Light, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Midlight, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Dark, brush8);
        palette3.setBrush(QPalette::Disabled, QPalette::Mid, brush9);
        palette3.setBrush(QPalette::Disabled, QPalette::Text, brush10);
        palette3.setBrush(QPalette::Disabled, QPalette::BrightText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ButtonText, brush10);
        palette3.setBrush(QPalette::Disabled, QPalette::Base, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Window, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::Shadow, brush6);
        palette3.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush7);
        palette3.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush6);
        currentweightedit->setPalette(palette3);
        QFont font5;
        font5.setFamily(QString::fromUtf8("Arial Unicode MS"));
        font5.setPointSize(20);
        font5.setBold(true);
        font5.setWeight(75);
        currentweightedit->setFont(font5);
        currentweightedit->setAutoFillBackground(true);
        currentweightedit->setStyleSheet(QString::fromUtf8("color: rgb(208, 0, 3);"));
        currentweightedit->setAlignment(Qt::AlignCenter);
        backgroundframe = new QFrame(centralWidget);
        backgroundframe->setObjectName(QString::fromUtf8("backgroundframe"));
        backgroundframe->setGeometry(QRect(460, 180, 371, 311));
        backgroundframe->setAutoFillBackground(false);
        backgroundframe->setStyleSheet(QString::fromUtf8("background-image: url(:/new/resource/background.png);"));
        backgroundframe->setFrameShape(QFrame::StyledPanel);
        backgroundframe->setFrameShadow(QFrame::Raised);
        headerlabel = new QLabel(centralWidget);
        headerlabel->setObjectName(QString::fromUtf8("headerlabel"));
        headerlabel->setGeometry(QRect(310, 50, 651, 51));
        QFont font6;
        font6.setFamily(QString::fromUtf8("Arial Unicode MS"));
        font6.setPointSize(36);
        font6.setBold(true);
        font6.setWeight(75);
        headerlabel->setFont(font6);
        headerlabel->setStyleSheet(QString::fromUtf8(""));
        headerlabel->setAlignment(Qt::AlignCenter);
        footerlabel = new QLabel(centralWidget);
        footerlabel->setObjectName(QString::fromUtf8("footerlabel"));
        footerlabel->setGeometry(QRect(450, 635, 371, 20));
        QFont font7;
        font7.setFamily(QString::fromUtf8("Arial Unicode MS"));
        font7.setPointSize(8);
        footerlabel->setFont(font7);
        footerlabel->setAlignment(Qt::AlignCenter);
        exmonthlabel = new QLabel(centralWidget);
        exmonthlabel->setObjectName(QString::fromUtf8("exmonthlabel"));
        exmonthlabel->setGeometry(QRect(1105, 635, 21, 21));
        QFont font8;
        font8.setFamily(QString::fromUtf8("Arial Unicode MS"));
        font8.setPointSize(10);
        font8.setBold(false);
        font8.setWeight(50);
        exmonthlabel->setFont(font8);
        exmonthlabel->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        exyearlabel = new QLabel(centralWidget);
        exyearlabel->setObjectName(QString::fromUtf8("exyearlabel"));
        exyearlabel->setGeometry(QRect(1135, 635, 41, 21));
        QFont font9;
        font9.setFamily(QString::fromUtf8("Arial Unicode MS"));
        exyearlabel->setFont(font9);
        expirylabel = new QLabel(centralWidget);
        expirylabel->setObjectName(QString::fromUtf8("expirylabel"));
        expirylabel->setGeometry(QRect(370, 506, 531, 20));
        QPalette palette4;
        QBrush brush11(QColor(255, 0, 0, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush11);
        palette4.setBrush(QPalette::Active, QPalette::Text, brush11);
        palette4.setBrush(QPalette::Active, QPalette::ButtonText, brush11);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush11);
        palette4.setBrush(QPalette::Inactive, QPalette::Text, brush11);
        palette4.setBrush(QPalette::Inactive, QPalette::ButtonText, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::Text, brush11);
        palette4.setBrush(QPalette::Disabled, QPalette::ButtonText, brush11);
        expirylabel->setPalette(palette4);
        QFont font10;
        font10.setBold(true);
        font10.setWeight(75);
        expirylabel->setFont(font10);
        expirylabel->setStyleSheet(QString::fromUtf8("color: rgb(255, 0, 0);"));
        expirylabel->setAlignment(Qt::AlignCenter);
        menugroupbox = new QGroupBox(centralWidget);
        menugroupbox->setObjectName(QString::fromUtf8("menugroupbox"));
        menugroupbox->setGeometry(QRect(20, 70, 101, 461));
        menugroupbox->setFont(font9);
        exitbutton = new QPushButton(menugroupbox);
        exitbutton->setObjectName(QString::fromUtf8("exitbutton"));
        exitbutton->setGeometry(QRect(20, 390, 61, 51));
        exitbutton->setAutoFillBackground(true);
        exitbutton->setIcon(icon6);
        exitbutton->setIconSize(QSize(37, 55));
        firstweightbutton = new QPushButton(menugroupbox);
        firstweightbutton->setObjectName(QString::fromUtf8("firstweightbutton"));
        firstweightbutton->setGeometry(QRect(20, 30, 61, 51));
        firstweightbutton->setAutoFillBackground(true);
        firstweightbutton->setIcon(icon1);
        firstweightbutton->setIconSize(QSize(52, 60));
        helpbutton = new QPushButton(menugroupbox);
        helpbutton->setObjectName(QString::fromUtf8("helpbutton"));
        helpbutton->setGeometry(QRect(20, 330, 61, 51));
        helpbutton->setAutoFillBackground(true);
        helpbutton->setIcon(icon5);
        helpbutton->setIconSize(QSize(43, 49));
        viewreportbutton = new QPushButton(menugroupbox);
        viewreportbutton->setObjectName(QString::fromUtf8("viewreportbutton"));
        viewreportbutton->setGeometry(QRect(20, 210, 61, 51));
        viewreportbutton->setAutoFillBackground(true);
        viewreportbutton->setIcon(icon3);
        viewreportbutton->setIconSize(QSize(45, 56));
        settingsbutton = new QPushButton(menugroupbox);
        settingsbutton->setObjectName(QString::fromUtf8("settingsbutton"));
        settingsbutton->setGeometry(QRect(20, 270, 61, 51));
        settingsbutton->setMinimumSize(QSize(0, 0));
        settingsbutton->setMouseTracking(false);
        settingsbutton->setFocusPolicy(Qt::StrongFocus);
        settingsbutton->setAutoFillBackground(true);
        settingsbutton->setIcon(icon4);
        settingsbutton->setIconSize(QSize(49, 60));
        viewticketbutton = new QPushButton(menugroupbox);
        viewticketbutton->setObjectName(QString::fromUtf8("viewticketbutton"));
        viewticketbutton->setGeometry(QRect(20, 150, 61, 51));
        viewticketbutton->setAutoFillBackground(true);
        viewticketbutton->setIcon(icon2);
        viewticketbutton->setIconSize(QSize(44, 60));
        secondweightbutton = new QPushButton(menugroupbox);
        secondweightbutton->setObjectName(QString::fromUtf8("secondweightbutton"));
        secondweightbutton->setGeometry(QRect(20, 90, 61, 51));
        secondweightbutton->setAutoFillBackground(true);
        secondweightbutton->setIcon(icon);
        secondweightbutton->setIconSize(QSize(52, 60));
        label = new QLabel(centralWidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(965, 635, 141, 20));
        QFont font11;
        font11.setFamily(QString::fromUtf8("Arial Unicode MS"));
        font11.setPointSize(9);
        font11.setBold(true);
        font11.setWeight(75);
        label->setFont(font11);
        label->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        exdateseperator = new QLabel(centralWidget);
        exdateseperator->setObjectName(QString::fromUtf8("exdateseperator"));
        exdateseperator->setGeometry(QRect(1120, 635, 20, 21));
        exdateseperator->setAlignment(Qt::AlignCenter);
        tare_groupbox = new QGroupBox(centralWidget);
        tare_groupbox->setObjectName(QString::fromUtf8("tare_groupbox"));
        tare_groupbox->setGeometry(QRect(20, 540, 101, 91));
        tare_button = new QPushButton(tare_groupbox);
        tare_button->setObjectName(QString::fromUtf8("tare_button"));
        tare_button->setGeometry(QRect(20, 20, 61, 51));
        tare_button->setFont(font10);
        tare_button->setAutoFillBackground(true);
        QIcon icon7;
        icon7.addFile(QString::fromUtf8(":/new/resource/tare.png"), QSize(), QIcon::Normal, QIcon::Off);
        tare_button->setIcon(icon7);
        tare_button->setIconSize(QSize(31, 56));
        MainWindow->setCentralWidget(centralWidget);
        menubar = new QToolBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setBaseSize(QSize(0, 0));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush6);
        palette5.setBrush(QPalette::Active, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Light, brush1);
        palette5.setBrush(QPalette::Active, QPalette::Midlight, brush1);
        QBrush brush12(QColor(150, 150, 150, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Dark, brush12);
        QBrush brush13(QColor(175, 175, 175, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::Mid, brush13);
        palette5.setBrush(QPalette::Active, QPalette::Text, brush6);
        palette5.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Active, QPalette::Base, brush);
        QBrush brush14(QColor(255, 170, 127, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Active, QPalette::AlternateBase, brush14);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Light, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Midlight, brush1);
        palette5.setBrush(QPalette::Inactive, QPalette::Dark, brush12);
        palette5.setBrush(QPalette::Inactive, QPalette::Mid, brush13);
        palette5.setBrush(QPalette::Inactive, QPalette::Text, brush6);
        palette5.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::Base, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush14);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush12);
        palette5.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Light, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Midlight, brush1);
        palette5.setBrush(QPalette::Disabled, QPalette::Dark, brush12);
        palette5.setBrush(QPalette::Disabled, QPalette::Mid, brush13);
        palette5.setBrush(QPalette::Disabled, QPalette::Text, brush12);
        palette5.setBrush(QPalette::Disabled, QPalette::ButtonText, brush12);
        QBrush brush15(QColor(239, 239, 239, 255));
        brush15.setStyle(Qt::SolidPattern);
        palette5.setBrush(QPalette::Disabled, QPalette::Base, brush15);
        palette5.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush14);
        menubar->setPalette(palette5);
        QFont font12;
        font12.setFamily(QString::fromUtf8("Arial Unicode MS"));
        font12.setPointSize(12);
        menubar->setFont(font12);
        menubar->setAcceptDrops(false);
        menubar->setAutoFillBackground(true);
        menubar->setMovable(false);
        menubar->setToolButtonStyle(Qt::ToolButtonTextBesideIcon);
        menubar->setFloatable(false);
        MainWindow->addToolBar(Qt::TopToolBarArea, menubar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QString::fromUtf8("statusBar"));
        MainWindow->setStatusBar(statusBar);
        QWidget::setTabOrder(firstweightbutton, secondweightbutton);
        QWidget::setTabOrder(secondweightbutton, viewticketbutton);
        QWidget::setTabOrder(viewticketbutton, viewreportbutton);
        QWidget::setTabOrder(viewreportbutton, settingsbutton);
        QWidget::setTabOrder(settingsbutton, helpbutton);
        QWidget::setTabOrder(helpbutton, exitbutton);

        menubar->addAction(actionFirst_Weight);
        menubar->addAction(actionSecond_Weight);
        menubar->addAction(actionView_Ticket);
        menubar->addAction(actionReport);
        menubar->addAction(actionSettings);
        menubar->addAction(actionHelp);
        menubar->addAction(actionExit);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "WEIGH BRIDGE", 0, QApplication::UnicodeUTF8));
        actionFirst_Weight->setText(QApplication::translate("MainWindow", "First Weight", 0, QApplication::UnicodeUTF8));
        actionSecond_Weight->setText(QApplication::translate("MainWindow", "Second Weight", 0, QApplication::UnicodeUTF8));
        actionView_Ticket->setText(QApplication::translate("MainWindow", "View Ticket", 0, QApplication::UnicodeUTF8));
        actionReport->setText(QApplication::translate("MainWindow", "Report", 0, QApplication::UnicodeUTF8));
        actionSettings->setText(QApplication::translate("MainWindow", "Settings", 0, QApplication::UnicodeUTF8));
        actionHelp->setText(QApplication::translate("MainWindow", "Help", 0, QApplication::UnicodeUTF8));
        actionExit->setText(QApplication::translate("MainWindow", "Exit", 0, QApplication::UnicodeUTF8));
        datelabel->setText(QApplication::translate("MainWindow", "Date", 0, QApplication::UnicodeUTF8));
        timelabel->setText(QApplication::translate("MainWindow", "Time", 0, QApplication::UnicodeUTF8));
        currentweightlabel->setText(QApplication::translate("MainWindow", "Current Weight (in KG)", 0, QApplication::UnicodeUTF8));
        currentdatetimelabel->setText(QApplication::translate("MainWindow", "Current Date & Time", 0, QApplication::UnicodeUTF8));
        currentdatetimeedit->setText(QString());
        currentweightedit->setText(QString());
        headerlabel->setText(QString());
        footerlabel->setText(QString());
        exmonthlabel->setText(QString());
        exyearlabel->setText(QString());
        expirylabel->setText(QString());
        menugroupbox->setTitle(QApplication::translate("MainWindow", "Menu", 0, QApplication::UnicodeUTF8));
        exitbutton->setText(QString());
        firstweightbutton->setText(QString());
        firstweightbutton->setShortcut(QString());
        helpbutton->setText(QString());
        viewreportbutton->setText(QString());
        settingsbutton->setText(QString());
        viewticketbutton->setText(QString());
#ifndef QT_NO_TOOLTIP
        secondweightbutton->setToolTip(QString());
#endif // QT_NO_TOOLTIP
#ifndef QT_NO_WHATSTHIS
        secondweightbutton->setWhatsThis(QString());
#endif // QT_NO_WHATSTHIS
        secondweightbutton->setText(QString());
        label->setText(QApplication::translate("MainWindow", "Licence Expiry :", 0, QApplication::UnicodeUTF8));
        exdateseperator->setText(QApplication::translate("MainWindow", "/", 0, QApplication::UnicodeUTF8));
        tare_groupbox->setTitle(QString());
        tare_button->setText(QString());
        menubar->setWindowTitle(QApplication::translate("MainWindow", "toolBar", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
